Repository FIWARE/keycloak-vc-issuer, pull requests merged in 2023-08, with the labels that each got.

#25 fix test init
  .github/workflows/compat-matrix.yml
  .github/workflows/integration-test.yml
  .gitignore
  .idea/.gitignore
  pom.xml
  src/main/java/org/fiware/keycloak/VCIssuerRealmResourceProvider.java
  src/main/java/org/fiware/keycloak/model/VCClaims.java
  src/test/java/org/fiware/keycloak/it/SIOP2IntegrationTest.java
  src/test/java/org/fiware/keycloak/it/model/CredentialObject.java
  src/test/java/org/fiware/keycloak/it/model/CredentialSchema.java
  src/test/java/org/fiware/keycloak/it/model/CredentialSubject.java
  src/test/java/org/fiware/keycloak/it/model/JWSProof.java
  src/test/java/org/fiware/keycloak/it/model/Role.java
  src/test/java/org/fiware/keycloak/it/model/VerifiableCredential.java
  src/test/k3s/keycloak.yaml
  src/test/k3s/waltid.yaml
Labels: minor

#27 Cred offer qr code
  .gitignore
  README.md
  api/api.yaml
  src/main/java/org/fiware/keycloak/VCIssuerRealmResourceProvider.java
  src/main/java/org/fiware/keycloak/model/walt/CredentialOfferURI.java
  src/test/java/org/fiware/keycloak/it/SIOP2IntegrationTest.java
  theme/siop-2/account/src/app/content/vc/VC.tsx
Labels: minor

#30 Truncated time to milliseconds
  src/main/java/org/fiware/keycloak/VCIssuerRealmResourceProvider.java
Labels: major

#32 Temporary commented out buggy waltid call
  src/main/java/org/fiware/keycloak/VCIssuerRealmResourceProvider.java
Labels: patch
